### ISSUE TITLE
build encounter error

### ISSUE THREAD

**Issue by dandingol03** [sourcechord/electron-monaco-editor-sample#1]
the error below:
index.ts(2,27): error TS2307: Cannot find module 'electron'.
index.ts(3,22): error TS2307: Cannot find module 'electron'.
main.ts(2,34): error TS2307: Cannot find module 'electron'.
main.ts(5,17): error TS2503: Cannot find namespace 'Electron'.
main.ts(10,7): error TS2304: Cannot find name 'process'.
main.ts(20,34): error TS2304: Cannot find name '__dirname'.

**Comment by sourcechord** [comment]
Hi, dandingol03!!

This sample uses `typings` for managing TypeScript definitions.
You have to install typings globally, and run `typings install` command.

Please try again, after run below commands.
```
npm install typings -g
typings install
```

**Comment by sourcechord** [comment]
Updated TypeScript&Electron packages. And, remove dependency for typings.
Now, There is no need to install typings.

This project can run with `npm install && npm start`.
